name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md,mdx}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Check IDs
        # check all mdx files have an id: tag matching the filename
        run: |
          ./check-id.py $(find . -name '*.mdx' | sort)

      - name: Check Linux SDK links
        run: |
          ./check-linux-sdk-links.sh

  # For pull requests generated from a fork, we run the prettier linter
  # but leave it up to the user to fix locally since we would need extra
  # permissions to be able to push a auto-fix commit to the forked repo
  prettier-fork:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md,mdx}
          dry: true
